[sncast.sepolia]
url = "https://rpc.starknet-testnet.lava.build"
account = "bitcoil"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true

[sncast.devnet]
account = "devnet-deployer"
network = "devnet"
