[sncast.sepolia]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
accounts-file = "accounts.json"
account = "deployer"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true
